# Copyright (c) 2026 by Haizy Tiles
#Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# ---------------------------------------------------------------------------
# Tag Cloud
# Main categories
# ---------------------------------------------------------------------------
GENRE_TAGS = {
    "Blues":        ["blues", "guitar", "soulful", "raw", "emotional", "classic", "roots", "acoustic"],
    "Classical":    ["orchestral", "instrumental", "composed", "elegant", "timeless", "symphony", "piano"],
    "Country":      ["country", "acoustic", "guitar", "storytelling", "americana", "roots", "twang"],
    "Electronic":   ["electronic", "synthesizer", "beats", "dance", "digital", "atmospheric", "club", "bass"],
    "Experimental": ["experimental", "avant-garde", "abstract", "unconventional", "noise", "art", "complex"],
    "Folk":         ["folk", "acoustic", "storytelling", "roots", "organic", "fingerpicking", "traditional"],
    "Funk":         ["funk", "groove", "bass", "rhythmic", "danceable", "soul", "upbeat", "syncopated"],
    "Hip-Hop":      ["hip-hop", "rap", "beats", "rhythm", "urban", "lyrical", "street", "bass", "flow"],
    "Jazz":         ["jazz", "improvisation", "saxophone", "swing", "complex", "piano", "brass", "sophisticated"],
    "Latin":        ["latin", "rhythm", "percussion", "dance", "passionate", "tropical", "vibrant", "festive"],
    "Metal":        ["metal", "heavy", "guitar", "distortion", "aggressive", "intense", "drums", "powerful"],
    "Pop":          ["pop", "catchy", "melodic", "upbeat", "radio-friendly", "polished", "contemporary"],
    "R&B":          ["r&b", "soulful", "groove", "smooth", "vocal", "rhythm", "urban", "emotional"],
    "Reggae":       ["reggae", "groove", "bass", "offbeat", "relaxed", "island", "roots", "positive"],
    "Rock":         ["rock", "guitar", "drums", "energetic", "band", "electric", "live", "powerful"],
    "Soul":         ["soul", "emotional", "vocal", "gospel", "soulful", "heartfelt", "rhythm", "expressive"],
}

# ---------------------------------------------------------------------------
# SubStyle Tags
# ---------------------------------------------------------------------------
SUBSTYLE_TAGS = {
    # =========================================================================
    # R O C K
    # =========================================================================
    "AOR": ["aor", "album oriented rock", "melodic", "70s", "80s", "mood:energetic", "mood:polished"],
    "Acid Rock": ["acid rock", "psychedelic", "improvisation", "60s", "guitar", "mood:trippy", "mood:energetic"],
    "Acoustic": ["acoustic", "unplugged", "intimate", "singer-songwriter", "mood:relaxed", "mood:melancholic"],
    "Alternative Rock": ["alternative", "indie", "guitar-driven", "90s", "mood:energetic", "mood:melancholic"],
    "Arena Rock": ["arena rock", "anthemic", "stadium", "powerful", "70s", "80s", "mood:epic", "mood:energetic"],
    "Art Rock": ["art rock", "progressive", "experimental", "conceptual", "mood:complex", "mood:epic"],
    "Atmospheric Black Metal": ["atmospheric black metal", "bm", "atmospheric", "blast beat", "screaming", "cold", "mood:dark", "mood:epic"],
    "Avantgarde": ["avantgarde", "experimental", "avant-garde", "abstract", "unconventional", "mood:complex", "mood:tense"],
    "Beat": ["beat", "merseybeat", "60s", "british", "rock and roll", "pop", "mood:happy", "mood:energetic"],
    "Black Metal": ["black metal", "atmospheric", "dark", "raw", "cold", "tremolo", "mood:dark", "mood:aggressive"],
    "Blues Rock": ["blues rock", "guitar", "riff", "soulful", "60s", "70s", "mood:energetic", "mood:soulful"],
    "Brit Pop": ["britpop", "british", "guitar", "90s", "catchy", "mood:happy", "mood:melancholic"],
    "Classic Rock": ["classic rock", "guitar", "60s", "70s", "timeless", "mood:energetic", "mood:nostalgic"],
    "Coldwave": ["coldwave", "cold", "minimal", "dark", "synth", "mood:dark", "mood:tense"],
    "Country Rock": ["country rock", "acoustic", "guitar", "americana", "roots", "mood:nostalgic", "mood:relaxed"],
    "Crust": ["crust", "crust punk", "heavy", "d-beat", "raw", "anarcho", "mood:aggressive", "mood:dark"],
    "Death Metal": ["death metal", "brutal", "extreme", "technical", "growl", "mood:aggressive", "mood:dark"],
    "Deathcore": ["deathcore", "metalcore", "death metal", "breakdown", "heavy", "mood:aggressive", "mood:brutal"],
    "Deathrock": ["deathrock", "gothic", "punk", "dark", "mood:dark", "mood:aggressive"],
    "Depressive Black Metal": ["dsbm", "depressive black metal", "sad", "melancholic", "atmospheric", "mood:dark", "mood:melancholic"],
    "Doo Wop": ["doo wop", "vocal", "harmony", "50s", "romantic", "mood:romantic", "mood:nostalgic"],
    "Doom Metal": ["doom metal", "slow", "heavy", "dark", "melancholic", "mood:dark", "mood:melancholic"],
    "Dream Pop": ["dream pop", "dreamy", "ethereal", "shoegaze", "reverb", "mood:dreamy", "mood:melancholic"],
    "Emo": ["emo", "emotional", "confessional", "guitar", "mood:sad", "mood:melancholic"],
    "Ethereal": ["ethereal", "dreamy", "atmospheric", "gothic", "female vocals", "mood:dreamy", "mood:dark"],
    "Experimental": ["experimental", "avant-garde", "abstract", "unconventional", "noise", "art", "complex"],
    "Folk Metal": ["folk metal", "metal", "folk", "melodic", "fiddle", "flute", "mood:epic", "mood:energetic"],
    "Folk Rock": ["folk rock", "acoustic", "electric", "storytelling", "mood:energetic", "mood:nostalgic"],
    "Funeral Doom Metal": ["funeral doom", "doom metal", "slow", "heavy", "funeral", "dirge", "mood:dark", "mood:melancholic"],
    "Funk Metal": ["funk metal", "funk", "metal", "rhythmic", "bass", "90s", "mood:groovy", "mood:aggressive"],
    "Garage Rock": ["garage rock", "raw", "lo-fi", "60s", "energetic", "mood:energetic", "mood:raw"],
    "Glam": ["glam rock", "glam", "theatrical", "70s", "anthemic", "mood:happy", "mood:energetic"],
    "Goregrind": ["goregrind", "grindcore", "gore", "brutal", "fast", "mood:aggressive", "mood:brutal"],
    "Goth Rock": ["goth rock", "dark", "atmospheric", "brooding", "mood:dark", "mood:melancholic", "mood:brooding"],
    "Gothic Metal": ["gothic metal", "gothic", "metal", "dark", "melodic", "female vocals", "mood:dark", "mood:melancholic"],
    "Grindcore": ["grindcore", "fast", "aggressive", "blast beat", "hardcore", "mood:aggressive", "mood:brutal"],
    "Grunge": ["grunge", "distorted", "raw", "90s", "seattle", "mood:dark", "mood:melancholic"],
    "Hard Rock": ["hard rock", "riff", "powerful", "guitar", "classic", "mood:energetic", "mood:powerful"],
    "Hardcore": ["hardcore punk", "fast", "aggressive", "raw", "shouting", "mood:aggressive", "mood:energetic"],
    "Heavy Metal": ["heavy metal", "metal", "guitar", "riff", "70s", "80s", "mood:powerful", "mood:energetic"],
    "Indie Rock": ["indie rock", "indie", "lo-fi", "underground", "diy", "guitar", "mood:relaxed", "mood:melancholic"],
    "Industrial": ["industrial rock", "industrial", "harsh", "mechanical", "dark", "mood:aggressive", "mood:dark"],
    "Krautrock": ["krautrock", "german", "experimental", "progressive", "motorik", "70s", "mood:trippy", "mood:complex"],
    "Lo-Fi": ["lo-fi", "chill", "relaxed", "nostalgic", "study", "mood:relaxed", "mood:melancholic"],
    "Lounge": ["lounge", "easy listening", "sophisticated", "smooth", "60s", "mood:relaxed", "mood:sophisticated"],
    "Math Rock": ["math rock", "complex", "angular", "instrumental", "polyrhythm", "mood:complex", "mood:energetic"],
    "Melodic Death Metal": ["melodic death metal", "melodeath", "melodic", "gothenburg", "death metal", "mood:melancholic", "mood:aggressive"],
    "Melodic Hardcore": ["melodic hardcore", "hardcore", "melodic", "emotional", "punk", "mood:melancholic", "mood:energetic"],
    "Metalcore": ["metalcore", "metal", "hardcore", "breakdown", "heavy", "mood:aggressive", "mood:energetic"],
    "Mod": ["mod", "60s", "british", "beat", "soul", "r&b", "mood:happy", "mood:energetic"],
    "Neofolk": ["neofolk", "folk", "dark", "martial", "acoustic", "mood:dark", "mood:melancholic"],
    "New Wave": ["new wave", "synth", "post-punk", "80s", "angular", "cold", "mood:melancholic", "mood:tense"],
    "No Wave": ["no wave", "avant-garde", "noise", "dissonant", "nyc", "late 70s", "mood:tense", "mood:complex"],
    "Noise": ["noise rock", "noise", "harsh", "dissonant", "feedback", "mood:tense", "mood:aggressive"],
    "Noisecore": ["noisecore", "noise", "hardcore", "fast", "chaotic", "mood:aggressive", "mood:brutal"],
    "Nu Metal": ["nu metal", "rap metal", "heavy", "groove", "00s", "mood:aggressive", "mood:energetic"],
    "Oi": ["oi", "street punk", "working class", "anthemic", "chorus", "mood:energetic", "mood:aggressive"],
    "Parody": ["parody", "comedy", "humorous", "spoof", "mood:happy", "mood:funny"],
    "Pop Punk": ["pop punk", "catchy", "upbeat", "punk", "melodic", "mood:happy", "mood:energetic"],
    "Pop Rock": ["pop rock", "catchy", "melodic", "radio-friendly", "guitar", "mood:happy", "mood:energetic"],
    "Pornogrind": ["pornogrind", "grindcore", "goregrind", "brutal", "sexual", "mood:aggressive", "mood:brutal"],
    "Post Rock": ["post rock", "instrumental", "atmospheric", "build-up", "explosive", "mood:epic", "mood:melancholic"],
    "Post-Hardcore": ["post-hardcore", "hardcore", "experimental", "emotional", "screaming", "mood:melancholic", "mood:aggressive"],
    "Post-Metal": ["post-metal", "metal", "atmospheric", "sludge", "instrumental", "mood:epic", "mood:dark"],
    "Post-Punk": ["post-punk", "angular", "raw", "dark", "intellectual", "minimalist", "mood:tense", "mood:dark"],
    "Power Metal": ["power metal", "epic", "melodic", "fast", "fantasy", "mood:epic", "mood:energetic"],
    "Power Pop": ["power pop", "catchy", "melodic", "guitar", "pop", "60s", "70s", "mood:happy", "mood:energetic"],
    "Power Violence": ["powerviolence", "fast", "aggressive", "hardcore", "grindcore", "mood:aggressive", "mood:brutal"],
    "Prog Rock": ["prog rock", "progressive", "complex", "long-form", "art rock", "mood:epic", "mood:complex"],
    "Progressive Metal": ["progressive metal", "prog metal", "complex", "technical", "heavy", "mood:complex", "mood:epic"],
    "Psychedelic Rock": ["psychedelic rock", "psychedelic", "trippy", "dreamy", "reverb", "60s", "cosmic", "mood:dreamy", "mood:trippy"],
    "Psychobilly": ["psychobilly", "rockabilly", "punk", "horror", "upright bass", "mood:energetic", "mood:dark"],
    "Pub Rock": ["pub rock", "rock", "roots", "70s", "british", "energetic", "mood:energetic", "mood:raw"],
    "Punk": ["punk rock", "punk", "fast", "aggressive", "raw", "diy", "rebellious", "mood:aggressive", "mood:energetic"],
    "Rock & Roll": ["rock and roll", "rock & roll", "50s", "upbeat", "saxophone", "piano", "mood:happy", "mood:energetic"],
    "Rockabilly": ["rockabilly", "50s", "guitar", "slap bass", "rock and roll", "mood:happy", "mood:energetic"],
    "Shoegaze": ["shoegaze", "dreamy", "reverb", "layered", "walls of sound", "mood:dreamy", "mood:melancholic"],
    "Ska": ["ska rock", "ska", "offbeat", "brass", "upbeat", "mood:happy", "mood:energetic"],
    "Sludge Metal": ["sludge metal", "sludge", "doom", "hardcore", "heavy", "slow", "mood:dark", "mood:aggressive"],
    "Soft Rock": ["soft rock", "smooth", "melodic", "70s", "radio-friendly", "mood:relaxed", "mood:romantic"],
    "Southern Rock": ["southern rock", "blues rock", "country", "guitar", "usa", "mood:energetic", "mood:nostalgic"],
    "Space Rock": ["space rock", "spacey", "psychedelic", "ambient", "cosmic", "mood:dreamy", "mood:epic"],
    "Speed Metal": ["speed metal", "fast", "aggressive", "heavy metal", "thrash", "mood:energetic", "mood:aggressive"],
    "Stoner Rock": ["stoner rock", "fuzz", "heavy", "groovy", "psychedelic", "mood:groovy", "mood:trippy"],
    "Surf": ["surf rock", "surf", "instrumental", "reverb", "guitar", "60s", "mood:happy", "mood:energetic"],
    "Symphonic Rock": ["symphonic rock", "orchestral", "prog rock", "epic", "classical", "mood:epic", "mood:dramatic"],
    "Technical Death Metal": ["technical death metal", "tech death", "complex", "brutal", "progressive", "mood:aggressive", "mood:complex"],
    "Thrash": ["thrash metal", "thrash", "fast", "aggressive", "technical", "mood:aggressive", "mood:energetic"],
    "Twist": ["twist", "dance", "60s", "rock and roll", "upbeat", "mood:happy", "mood:energetic"],
    "Viking Metal": ["viking metal", "folk metal", "epic", "norse", "melodic", "mood:epic", "mood:aggressive"],
    "Yé-Yé": ["yé-yé", "french pop", "60s", "female vocals", "ye ye", "mood:happy", "mood:romantic"],

    # =========================================================================
    # E L E C T R O N I C
    # =========================================================================
    "Abstract": ["abstract", "experimental", "electronic", "sound collage", "glitch", "mood:complex", "mood:tense"],
    "Acid": ["acid", "acid house", "303", "squelchy", "electronic", "mood:trippy", "mood:energetic"],
    "Acid House": ["acid house", "house", "303", "chicago", "80s", "mood:happy", "mood:trippy"],
    "Acid Jazz": ["acid jazz", "jazz", "funk", "groovy", "electronic", "90s", "mood:groovy", "mood:relaxed"],
    "Ambient": ["ambient", "atmospheric", "drone", "meditative", "texture", "mood:relaxed", "mood:meditative"],
    "Bassline": ["bassline", "uk garage", "bass", "electronic", "dance", "mood:energetic", "mood:groovy"],
    "Beatdown": ["beatdown", "hardcore", "electronic", "slow", "heavy", "mood:aggressive", "mood:dark"],
    "Berlin-School": ["berlin school", "electronic", "sequencer", "kosmische", "70s", "mood:trippy", "mood:epic"],
    "Big Beat": ["big beat", "electronic", "breakbeat", "90s", "heavy", "chem bros", "mood:energetic", "mood:aggressive"],
    "Bleep": ["bleep", "electronic", "techno", "uk", "80s", "minimal", "mood:tense", "mood:energetic"],
    "Breakbeat": ["breakbeat", "electronic", "breaks", "dance", "funky", "mood:energetic", "mood:groovy"],
    "Breakcore": ["breakcore", "electronic", "fast", "breakbeat", "jungle", "noise", "mood:aggressive", "mood:complex"],
    "Breaks": ["breaks", "breakbeat", "electronic", "dance", "funky", "mood:energetic", "mood:groovy"],
    "Broken Beat": ["broken beat", "electronic", "jazz", "funk", "complex rhythms", "mood:groovy", "mood:complex"],
    "Chillwave": ["chillwave", "synth", "dreamy", "lo-fi", "nostalgic", "mood:relaxed", "mood:melancholic"],
    "Chiptune": ["chiptune", "8-bit", "video game", "electronic", "retro", "mood:happy", "mood:nostalgic"],
    "Dance-pop": ["dance-pop", "pop", "dance", "catchy", "electronic", "mood:happy", "mood:energetic"],
    "Dark Ambient": ["dark ambient", "ambient", "dark", "atmospheric", "drone", "industrial", "mood:dark", "mood:tense"],
    "Darkwave": ["darkwave", "electronic", "cold", "atmospheric", "gothic", "mood:dark", "mood:melancholic"],
    "Deep House": ["deep house", "soulful", "electronic", "groovy", "mood:relaxed", "mood:groovy"],
    "Deep Techno": ["deep techno", "techno", "minimal", "atmospheric", "hypnotic", "mood:tense", "mood:meditative"],
    "Disco": ["disco electronic", "disco", "dance", "funk", "70s", "groove", "upbeat", "mood:happy", "mood:energetic"],
    "Disco Polo": ["disco polo", "polish", "dance", "pop", "cheesy", "mood:happy", "mood:energetic"],
    "Donk": ["donk", "uk hard house", "bouncy", "energetic", "mood:energetic", "mood:happy"],
    "Downtempo": ["downtempo", "chill", "electronic", "relaxed", "mood:relaxed", "mood:melancholic"],
    "Drone": ["drone", "ambient", "minimal", "sustained", "experimental", "mood:meditative", "mood:tense"],
    "Drum n Bass": ["drum and bass", "dnb", "electronic", "fast", "breakbeat", "bass", "mood:energetic", "mood:tense"],
    "Dub": ["dub electronic", "dub", "reggae", "bass", "reverb", "echo", "instrumental", "mood:relaxed", "mood:trippy"],
    "Dub Techno": ["dub techno", "techno", "dub", "minimal", "deep", "reverb", "mood:relaxed", "mood:meditative"],
    "Dubstep": ["dubstep", "bass", "wobble", "electronic", "uk", "mood:dark", "mood:tense"],
    "Dungeon Synth": ["dungeon synth", "fantasy", "ambient", "lo-fi", "synthesizer", "medieval", "mood:dark", "mood:epic"],
    "EBM": ["ebm", "industrial", "electronic", "dark", "dance", "mood:aggressive", "mood:tense"],
    "Electro": ["electro", "electro-funk", "80s", "drum machine", "vocoder", "mood:energetic", "mood:groovy"],
    "Electro House": ["electro house", "electro", "house", "dirty", "bass", "mood:energetic", "mood:aggressive"],
    "Electroclash": ["electroclash", "synth", "punk", "fashion", "00s", "mood:ironic", "mood:energetic"],
    "Euro House": ["euro house", "eurodance", "dance", "pop", "90s", "mood:happy", "mood:energetic"],
    "Euro-Disco": ["euro disco", "disco", "synth", "70s", "80s", "catchy", "mood:happy", "mood:energetic"],
    "Eurobeat": ["eurobeat", "fast", "dance", "japanese", "italian", "mood:energetic", "mood:happy"],
    "Eurodance": ["eurodance", "dance", "rap", "female vocal", "90s", "mood:happy", "mood:energetic"],
    "Experimental": ["experimental electronic", "avant-garde", "abstract", "unconventional", "noise", "mood:complex", "mood:tense"],
    "Freestyle": ["freestyle", "latin", "electro", "80s", "dance", "mood:romantic", "mood:energetic"],
    "Future Jazz": ["future jazz", "jazz", "electronic", "nu jazz", "groovy", "mood:groovy", "mood:relaxed"],
    "Gabber": ["gabber", "gabba", "hardcore", "fast", "dutch", "mood:aggressive", "mood:brutal"],
    "Garage House": ["garage house", "house", "soulful", "new york", "vocal", "mood:happy", "mood:groovy"],
    "Ghetto": ["ghetto house", "ghetto tech", "booty", "minimal", "dance", "mood:energetic", "mood:aggressive"],
    "Ghetto House": ["ghetto house", "booty house", "minimal", "dance", "chicago", "mood:energetic", "mood:aggressive"],
    "Glitch": ["glitch", "electronic", "idm", "clicks", "cuts", "experimental", "mood:complex", "mood:tense"],
    "Goa Trance": ["goa trance", "trance", "psychedelic", "india", "90s", "mood:trippy", "mood:energetic"],
    "Grime": ["grime", "uk", "electronic", "rap", "bass", "dark", "mood:dark", "mood:aggressive"],
    "Halftime": ["halftime", "dnb", "drum and bass", "slow", "half-speed", "mood:dark", "mood:tense"],
    "Hands Up": ["hands up", "eurodance", "trance", "happy", "hardstyle", "mood:happy", "mood:energetic"],
    "Happy Hardcore": ["happy hardcore", "hardcore", "uk", "breakbeat", "happy", "piano", "mood:happy", "mood:energetic"],
    "Hard House": ["hard house", "uk hard house", "energetic", "bouncy", "mood:energetic", "mood:aggressive"],
    "Hard Techno": ["hard techno", "techno", "hard", "schranz", "industrial", "mood:aggressive", "mood:energetic"],
    "Hard Trance": ["hard trance", "trance", "hard", "rave", "energetic", "mood:energetic", "mood:euphoric"],
    "Hardcore": ["hardcore electronic", "gabber", "techno", "fast", "industrial", "mood:aggressive", "mood:brutal"],
    "Hardstyle": ["hardstyle", "hard dance", "hard trance", "hardcore", "reverse bass", "mood:energetic", "mood:euphoric"],
    "Hi NRG": ["hi-nrg", "high energy", "disco", "dance", "80s", "fast", "mood:happy", "mood:energetic"],
    "Hip Hop": ["hip hop electronic", "electro", "rap", "beats", "urban", "mood:energetic", "mood:street"],
    "Hip-House": ["hip-house", "hip hop", "house", "dance", "90s", "mood:happy", "mood:energetic"],
    "House": ["house", "dance", "electronic", "club", "four-on-the-floor", "mood:euphoric", "mood:energetic"],
    "IDM": ["idm", "electronic", "intelligent", "complex", "glitch", "experimental", "mood:complex", "mood:tense"],
    "Illbient": ["illbient", "ambient", "dub", "hip hop", "downtown", "nyc", "mood:dark", "mood:trippy"],
    "Industrial": ["industrial electronic", "industrial", "harsh", "mechanical", "dark", "ebm", "mood:aggressive", "mood:dark"],
    "Italo House": ["italo house", "house", "italian", "piano", "melodic", "mood:happy", "mood:energetic"],
    "Italo-Disco": ["italo-disco", "disco", "synth", "electronic", "80s", "dance", "mood:happy", "mood:energetic"],
    "Italodance": ["italodance", "eurodance", "italian", "melodic", "90s", "mood:happy", "mood:energetic"],
    "Jazzdance": ["jazzdance", "jazz", "dance", "funk", "electronic", "mood:groovy", "mood:sophisticated"],
    "Juke": ["juke", "footwork", "chicago", "fast", "electronic", "mood:energetic", "mood:tense"],
    "Jumpstyle": ["jumpstyle", "hard dance", "energetic", "jump", "belgium", "netherlands", "mood:energetic", "mood:happy"],
    "Jungle": ["jungle", "drum and bass", "breakbeat", "ragga", "uk", "bass", "mood:energetic", "mood:dark"],
    "Latin": ["latin electronic", "electro-latin", "dance", "rhythm", "mood:happy", "mood:energetic"],
    "Leftfield": ["leftfield", "electronic", "experimental", "ambient", "dub", "mood:complex", "mood:trippy"],
    "Makina": ["makina", "hardcore", "techno", "spanish", "fast", "mood:energetic", "mood:aggressive"],
    "Minimal": ["minimal", "techno", "house", "repetitive", "reductionist", "mood:tense", "mood:meditative"],
    "Minimal Techno": ["minimal techno", "techno", "minimal", "detroit", "hypnotic", "mood:tense", "mood:meditative"],
    "Modern Classical": ["modern classical", "contemporary", "classical", "electronic", "minimal", "mood:complex", "mood:melancholic"],
    "Musique Concrète": ["musique concrète", "experimental", "electronic", "tape", "sound collage", "mood:complex", "mood:tense"],
    "Neofolk": ["neofolk electronic", "neofolk", "dark", "martial", "industrial", "mood:dark", "mood:melancholic"],
    "New Age": ["new age", "relaxation", "ambient", "meditation", "spiritual", "mood:relaxed", "mood:meditative"],
    "New Beat": ["new beat", "belgian", "electronic", "ebm", "house", "slow", "mood:dark", "mood:tense"],
    "New Wave": ["new wave", "synth", "post-punk", "80s", "angular", "cold", "mood:melancholic", "mood:tense"],
    "Noise": ["noise electronic", "harsh noise", "industrial", "experimental", "abrasive", "mood:aggressive", "mood:tense"],
    "Nu-Disco": ["nu-disco", "disco", "electronic", "funky", "contemporary", "mood:happy", "mood:groovy"],
    "Power Electronics": ["power electronics", "industrial", "harsh", "confrontational", "noise", "mood:aggressive", "mood:dark"],
    "Progressive Breaks": ["progressive breaks", "breaks", "progressive", "electronic", "building", "mood:epic", "mood:energetic"],
    "Progressive House": ["progressive house", "house", "progressive", "building", "melodic", "mood:euphoric", "mood:epic"],
    "Progressive Trance": ["progressive trance", "trance", "progressive", "building", "melodic", "mood:euphoric", "mood:epic"],
    "Psy-Trance": ["psytrance", "psychedelic", "trance", "fast", "trippy", "bass", "mood:trippy", "mood:energetic"],
    "Rhythmic Noise": ["rhythmic noise", "industrial", "noise", "rhythmic", "harsh", "mood:aggressive", "mood:dark"],
    "Schranz": ["schranz", "techno", "hard", "fast", "minimal", "german", "mood:aggressive", "mood:energetic"],
    "Sound Collage": ["sound collage", "experimental", "electronic", "samples", "plunderphonics", "mood:complex", "mood:abstract"],
    "Speed Garage": ["speed garage", "uk garage", "fast", "bass", "electronic", "mood:energetic", "mood:groovy"],
    "Speedcore": ["speedcore", "hardcore", "fast", "extreme", "brutal", "mood:aggressive", "mood:brutal"],
    "Synth-pop": ["synth-pop", "synth", "electronic", "80s", "pop", "catchy", "danceable", "mood:happy", "mood:energetic"],
    "Synthwave": ["synthwave", "80s", "retro", "synth", "electronic", "nostalgic", "mood:nostalgic", "mood:energetic"],
    "Tech House": ["tech house", "techno", "house", "minimal", "groovy", "mood:energetic", "mood:groovy"],
    "Tech Trance": ["tech trance", "trance", "techno", "driving", "energetic", "mood:energetic", "mood:euphoric"],
    "Techno": ["techno", "electronic", "minimalist", "repetitive", "industrial", "mood:tense", "mood:energetic"],
    "Trance": ["trance", "electronic", "euphoric", "melodic", "mood:euphoric", "mood:energetic"],
    "Tribal": ["tribal", "electronic", "drums", "ethnic", "rhythm", "mood:energetic", "mood:primal"],
    "Tribal House": ["tribal house", "house", "tribal", "drums", "deep", "mood:groovy", "mood:energetic"],
    "Trip Hop": ["trip hop", "downtempo", "hip-hop", "electronic", "moody", "mood:dark", "mood:relaxed"],
    "Tropical House": ["tropical house", "house", "tropical", "relaxed", "beach", "mood:happy", "mood:relaxed"],
    "UK Garage": ["uk garage", "ukg", "garage", "2-step", "bass", "mood:groovy", "mood:energetic"],
    "Vaporwave": ["vaporwave", "vapor", "aesthetic", "80s", "90s", "mallsoft", "mood:nostalgic", "mood:dreamy"],
    # =========================================================================
    # J A Z Z
    # =========================================================================
    "Afro-Cuban Jazz": ["afro-cuban", "jazz", "latin", "percussion", "rhythm", "mood:energetic", "mood:happy"],
    "Afrobeat": ["afrobeat", "african", "funk", "jazz", "highlife", "percussion", "mood:energetic", "mood:groovy"],
    "Avant-garde Jazz": ["avant-garde jazz", "free jazz", "experimental", "improvisation", "abstract", "mood:complex", "mood:tense"],
    "Big Band": ["big band", "swing", "orchestra", "brass", "saxophone", "mood:energetic", "mood:sophisticated"],
    "Bop": ["bebop", "fast", "complex", "improvisation", "jazz", "mood:energetic", "mood:complex"],
    "Bossa Nova": ["bossa nova", "latin", "smooth", "jazz", "acoustic", "relaxed", "mood:relaxed", "mood:romantic"],
    "Contemporary Jazz": ["contemporary jazz", "modern", "smooth", "fusion", "electronic", "mood:relaxed", "mood:sophisticated"],
    "Cool Jazz": ["cool jazz", "relaxed", "sophisticated", "mood:relaxed", "mood:sophisticated"],
    "Dixieland": ["dixieland", "traditional jazz", "new orleans", "brass", "ensemble", "mood:happy", "mood:energetic"],
    "Easy Listening": ["easy listening", "lounge", "smooth", "orchestral", "instrumental", "mood:relaxed", "mood:pleasant"],
    "Free Improvisation": ["free improvisation", "improvisation", "avant-garde", "experimental", "spontaneous", "mood:complex", "mood:tense"],
    "Free Jazz": ["free jazz", "improvisation", "experimental", "avant-garde", "mood:tense", "mood:complex"],
    "Fusion": ["jazz fusion", "fusion", "complex", "jazz", "rock", "electric", "mood:energetic", "mood:complex"],
    "Gypsy Jazz": ["gypsy jazz", "gypsy", "swing", "acoustic", "guitar", "violin", "mood:happy", "mood:energetic"],
    "Hard Bop": ["hard bop", "blues", "gospel", "jazz", "mood:energetic", "mood:soulful"],
    "Jazz-Funk": ["jazz-funk", "funk", "groove", "electric", "rhythmic", "mood:groovy", "mood:energetic"],
    "Jazz-Rock": ["jazz-rock", "jazz", "rock", "fusion", "electric", "mood:energetic", "mood:complex"],
    "Latin Jazz": ["latin jazz", "latin", "jazz", "rhythm", "percussion", "mood:energetic", "mood:happy"],
    "Modal": ["modal jazz", "modal", "improvisation", "miles davis", "cool", "mood:relaxed", "mood:complex"],
    "Post Bop": ["post bop", "jazz", "hard bop", "avant-garde", "60s", "mood:complex", "mood:energetic"],
    "Ragtime": ["ragtime", "piano", "syncopation", "early", "1900s", "mood:happy", "mood:energetic"],
    "Smooth Jazz": ["smooth jazz", "relaxed", "polished", "mood:relaxed", "mood:happy"],
    "Soul-Jazz": ["soul jazz", "groove", "organ", "funky", "mood:groovy", "mood:happy"],
    "Space-Age": ["space age", "space age pop", "exotica", "lounge", "futuristic", "50s", "60s", "mood:dreamy", "mood:nostalgic"],
    "Swing": ["swing", "big band", "dance", "jazz", "40s", "mood:happy", "mood:energetic"],

    # =========================================================================
    # F O L K,  W O R L D,  &  C O U N T R Y
    # =========================================================================
    "African": ["african", "world", "traditional", "percussion", "tribal", "mood:energetic", "mood:spiritual"],
    "Bluegrass": ["bluegrass", "acoustic", "banjo", "fiddle", "country", "roots", "mood:happy", "mood:energetic"],
    "Cajun": ["cajun", "louisiana", "french", "accordion", "fiddle", "folk", "mood:happy", "mood:energetic"],
    "Canzone Napoletana": ["canzone napoletana", "neapolitan", "italian", "traditional", "vocal", "romantic", "mood:romantic", "mood:melancholic"],
    "Catalan Music": ["catalan", "spain", "folk", "traditional", "regional", "mood:nostalgic", "mood:cultural"],
    "Celtic": ["celtic", "irish", "scottish", "folk", "fiddle", "whistle", "mood:happy", "mood:energetic"],
    "Country": ["country", "acoustic", "guitar", "storytelling", "americana", "roots", "twang"],
    "Fado": ["fado", "portuguese", "sad", "melancholic", "vocal", "guitar", "mood:melancholic", "mood:sad"],
    "Flamenco": ["flamenco", "spanish", "guitar", "clapping", "dance", "passionate", "mood:passionate", "mood:energetic"],
    "Folk": ["folk", "acoustic", "storytelling", "roots", "organic", "fingerpicking", "traditional"],
    "Gospel": ["gospel folk", "spiritual", "religious", "choir", "southern", "mood:uplifting", "mood:happy"],
    "Highlife": ["highlife", "ghanaian", "african", "guitar", "dance", "jazz", "mood:happy", "mood:energetic"],
    "Hillbilly": ["hillbilly", "old-time", "country", "folk", "appalachian", "string band", "mood:happy", "mood:nostalgic"],
    "Hindustani": ["hindustani", "indian classical", "north indian", "raga", "sitar", "tabla", "mood:spiritual", "mood:meditative"],
    "Honky Tonk": ["honky tonk", "country", "piano", "bar", "drinking", "twang", "mood:happy", "mood:sad"],
    "Indian Classical": ["indian classical", "raga", "sitar", "tabla", "traditional", "spiritual", "mood:spiritual", "mood:meditative"],
    "Laïkó": ["laiko", "greek", "folk", "pop", "bouzouki", "mood:melancholic", "mood:energetic"],
    "Nordic": ["nordic", "scandinavian", "folk", "traditional", "cold", "mood:melancholic", "mood:nostalgic"],
    "Pacific": ["pacific", "oceanic", "polynesian", "hawaiian", "island", "folk", "mood:relaxed", "mood:happy"],
    "Polka": ["polka", "dance", "accordion", "eastern european", "happy", "mood:happy", "mood:energetic"],
    "Raï": ["rai", "algerian", "north african", "folk", "pop", "arabic", "mood:energetic", "mood:melancholic"],
    "Romani": ["romani", "gypsy", "folk", "balkan", "violin", "passionate", "mood:passionate", "mood:energetic"],
    "Soukous": ["soukous", "congolese", "african", "dance", "guitar", "rhumba", "mood:happy", "mood:energetic"],
    "Séga": ["sega", "mauritian", "island", "folk", "dance", "percussion", "mood:happy", "mood:relaxed"],
    "Volksmusik": ["volksmusik", "german", "folk", "traditional", "alpine", "oompah", "mood:happy", "mood:nostalgic"],
    "Zouk": ["zouk", "caribbean", "french antilles", "dance", "romantic", "mood:romantic", "mood:happy"],
    "Éntekhno": ["entekhno", "greek", "art music", "folk", "orchestral", "mood:melancholic", "mood:sophisticated"],

    # =========================================================================
    # F U N K  /  S O U L
    # =========================================================================
    "Afrobeat": ["afrobeat", "funk", "african", "percussion", "political", "fela", "mood:energetic", "mood:groovy"],
    "Boogie": ["boogie", "post-disco", "funk", "electronic", "80s", "mood:groovy", "mood:happy"],
    "Contemporary R&B": ["contemporary r&b", "r&b", "soulful", "smooth", "modern", "urban", "mood:romantic", "mood:groovy"],
    "Disco": ["disco funk", "disco", "dance", "funk", "70s", "groove", "upbeat", "mood:happy", "mood:energetic"],
    "Free Funk": ["free funk", "funk", "improvisation", "avant-garde", "experimental", "mood:complex", "mood:groovy"],
    "Funk": ["funk", "groove", "bass", "rhythmic", "mood:groovy", "mood:energetic"],
    "Gospel": ["gospel soul", "gospel", "spiritual", "soul", "choir", "religious", "mood:uplifting", "mood:happy"],
    "Neo Soul": ["neo soul", "soulful", "smooth", "contemporary", "mood:relaxed", "mood:soulful"],
    "New Jack Swing": ["new jack swing", "rnb", "hip hop", "swing", "80s", "90s", "mood:energetic", "mood:groovy"],
    "P.Funk": ["p-funk", "parliament", "funkadelic", "funk", "psychedelic", "groovy", "mood:trippy", "mood:groovy"],
    "Psychedelic": ["psychedelic soul", "psychedelic", "soul", "funk", "trippy", "60s", "70s", "mood:trippy", "mood:groovy"],
    "Rhythm & Blues": ["rhythm and blues", "r&b", "blues", "soulful", "dance", "40s", "50s", "mood:energetic", "mood:romantic"],
    "Soul": ["soul", "emotional", "vocal", "gospel", "soulful", "heartfelt", "rhythm", "expressive"],
    "Swingbeat": ["swingbeat", "new jack swing", "rnb", "slow jam", "mood:romantic", "mood:groovy"],
    "UK Street Soul": ["uk street soul", "british", "r&b", "soul", "90s", "urban", "mood:soulful", "mood:relaxed"],

    # =========================================================================
    # H I P  H O P
    # =========================================================================
    "Bass Music": ["bass music", "uk bass", "electronic", "bass heavy", "club", "mood:energetic", "mood:dark"],
    "Boom Bap": ["boom bap", "sampling", "jazz", "90s", "conscious", "mood:energetic", "mood:nostalgic"],
    "Bounce": ["bounce", "new orleans", "hip hop", "energetic", "call and response", "mood:happy", "mood:energetic"],
    "Britcore": ["britcore", "uk", "hardcore", "hip hop", "90s", "mood:aggressive", "mood:energetic"],
    "Cloud Rap": ["cloud rap", "atmospheric", "dreamy", "hip hop", "chill", "mood:dreamy", "mood:relaxed"],
    "Conscious": ["conscious hip hop", "political", "social", "awareness", "lyrical", "mood:thoughtful", "mood:energetic"],
    "Crunk": ["crunk", "southern hip hop", "energetic", "club", "00s", "mood:energetic", "mood:aggressive"],
    "Cut-up/DJ": ["cut-up", "dj", "turntablism", "scratching", "samples", "mood:energetic", "mood:complex"],
    "DJ Battle Tool": ["dj battle tool", "turntablism", "scratching", "beats", "instrumental", "mood:energetic", "mood:complex"],
    "Electro": ["electro hip hop", "electro", "hip hop", "80s", "drum machine", "mood:energetic", "mood:groovy"],
    "G-Funk": ["g-funk", "west coast", "funk", "synth", "90s", "mood:groovy", "mood:relaxed"],
    "Gangsta": ["gangsta rap", "west coast", "street", "aggressive", "lyrical", "mood:aggressive", "mood:dark"],
    "Grime": ["grime hip hop", "uk", "electronic", "rap", "bass", "dark", "mood:dark", "mood:aggressive"],
    "Hardcore Hip-Hop": ["hardcore hip hop", "aggressive", "raw", "street", "east coast", "mood:aggressive", "mood:energetic"],
    "Horrorcore": ["horrorcore", "horror", "rap", "dark", "violent", "mood:dark", "mood:scary"],
    "Instrumental": ["instrumental hip hop", "beats", "instrumental", "dj", "producer", "mood:relaxed", "mood:energetic"],
    "Jazzy Hip-Hop": ["jazz rap", "jazzy", "hip hop", "samples", "conscious", "mood:relaxed", "mood:sophisticated"],
    "Miami Bass": ["miami bass", "booty bass", "bass heavy", "dance", "electro", "mood:energetic", "mood:happy"],
    "Pop Rap": ["pop rap", "pop", "hip hop", "catchy", "radio-friendly", "mood:happy", "mood:energetic"],
    "Ragga HipHop": ["ragga hip hop", "ragga", "dancehall", "hip hop", "jamaican", "mood:energetic", "mood:happy"],
    "RnB/Swing": ["rnb swing", "new jack swing", "r&b", "hip hop", "mood:romantic", "mood:groovy"],
    "Screw": ["screw", "chopped and screwed", "houston", "slow", "hip hop", "mood:trippy", "mood:dark"],
    "Thug Rap": ["thug rap", "gangsta", "southern", "street", "mood:aggressive", "mood:dark"],
    "Trap": ["trap", "808s", "hi-hats", "dark", "urban", "mood:dark", "mood:tense"],
    "Trip Hop": ["trip hop hip hop", "trip hop", "downtempo", "bristol", "moody", "mood:dark", "mood:relaxed"],
    "Turntablism": ["turntablism", "dj", "scratching", "beats", "technical", "mood:energetic", "mood:complex"],
        # =========================================================================
    # L A T I N
    # =========================================================================
    "Afro-Cuban": ["afro-cuban", "latin", "rhythm", "percussion", "cuban", "mood:energetic", "mood:happy"],
    "Baião": ["baiao", "brazilian", "northeastern", "accordion", "triangle", "mood:happy", "mood:energetic"],
    "Batucada": ["batucada", "brazilian", "percussion", "samba", "carnival", "mood:energetic", "mood:happy"],
    "Beguine": ["beguine", "latin", "dance", "caribbean", "romantic", "mood:romantic", "mood:happy"],
    "Bolero": ["bolero", "latin", "romantic", "slow", "orchestral", "mood:romantic", "mood:melancholic"],
    "Boogaloo": ["boogaloo", "latin", "soul", "funk", "60s", "nyc", "mood:happy", "mood:energetic"],
    "Bossanova": ["bossa nova", "latin", "smooth", "jazz", "acoustic", "relaxed", "mood:relaxed", "mood:romantic"],
    "Cha-Cha": ["cha-cha", "cuban", "dance", "rhythm", "mood:happy", "mood:energetic"],
    "Charanga": ["charanga", "cuban", "flute", "violin", "dance", "mood:happy", "mood:energetic"],
    "Compas": ["compas", "haitian", "dance", "méringue", "caribbean", "mood:happy", "mood:energetic"],
    "Cubano": ["cubano", "cuban", "son", "latin", "traditional", "mood:happy", "mood:rhythmic"],
    "Cumbia": ["cumbia", "colombian", "latin", "dance", "accordion", "mood:happy", "mood:energetic"],
    "Descarga": ["descarga", "cuban", "jam session", "improvisation", "latin jazz", "mood:energetic", "mood:complex"],
    "Forró": ["forro", "brazilian", "northeastern", "accordion", "dance", "mood:happy", "mood:energetic"],
    "Guaguancó": ["guaguanco", "cuban", "rumba", "percussion", "afro-cuban", "mood:energetic", "mood:rhythmic"],
    "Guajira": ["guajira", "cuban", "country", "folk", "latin", "mood:nostalgic", "mood:romantic"],
    "Guaracha": ["guaracha", "cuban", "upbeat", "theater", "comic", "mood:happy", "mood:energetic"],
    "MPB": ["mpb", "brazilian", "pop", "folk", "sophisticated", "mood:melancholic", "mood:thoughtful"],
    "Mambo": ["mambo", "cuban", "big band", "dance", "percussion", "mood:energetic", "mood:happy"],
    "Mariachi": ["mariachi", "mexican", "folk", "trumpet", "violin", "mood:happy", "mood:passionate"],
    "Merengue": ["merengue", "dominican", "dance", "fast", "accordion", "mood:happy", "mood:energetic"],
    "Norteño": ["norteno", "mexican", "accordion", "folk", "northern", "mood:happy", "mood:melancholic"],
    "Nueva Cancion": ["nueva cancion", "protest", "folk", "latin", "political", "mood:thoughtful", "mood:melancholic"],
    "Pachanga": ["pachanga", "cuban", "dance", "charanga", "60s", "mood:happy", "mood:energetic"],
    "Porro": ["porro", "colombian", "cumbia", "wind band", "dance", "mood:happy", "mood:energetic"],
    "Ranchera": ["ranchera", "mexican", "mariachi", "folk", "emotional", "mood:passionate", "mood:melancholic"],
    "Reggaeton": ["reggaeton", "latin", "urban", "dance", "dembow", "mood:energetic", "mood:happy"],
    "Rumba": ["rumba", "cuban", "afro-cuban", "percussion", "dance", "mood:energetic", "mood:rhythmic"],
    "Salsa": ["salsa", "latin", "dance", "percussion", "vibrant", "mood:happy", "mood:energetic"],
    "Samba": ["samba", "brazilian", "carnival", "percussion", "dance", "mood:happy", "mood:energetic"],
    "Son": ["son", "cuban", "roots", "guitar", "percussion", "mood:happy", "mood:nostalgic"],
    "Son Montuno": ["son montuno", "cuban", "son", "piano", "montuno", "mood:happy", "mood:energetic"],
    "Tango": ["tango", "passionate", "dramatic", "dance", "mood:tense", "mood:romantic"],
    "Tejano": ["tejano", "tex-mex", "accordion", "mexican-american", "mood:happy", "mood:energetic"],
    "Vallenato": ["vallenato", "colombian", "accordion", "folk", "storytelling", "mood:happy", "mood:melancholic"],

    # =========================================================================
    # P O P
    # =========================================================================
    "Ballad": ["ballad", "slow", "emotional", "vocal", "romantic", "mood:melancholic", "mood:romantic"],
    "Bollywood": ["bollywood", "indian", "film", "soundtrack", "colorful", "mood:happy", "mood:dramatic"],
    "Bubblegum": ["bubblegum", "pop", "catchy", "teen", "happy", "60s", "70s", "mood:happy", "mood:energetic"],
    "Chanson": ["chanson", "french", "vocal", "poetic", "lyrical", "mood:melancholic", "mood:romantic"],
    "City Pop": ["city pop", "japanese", "80s", "urban", "funk", "mood:nostalgic", "mood:groovy"],
    "Europop": ["europop", "pop", "european", "catchy", "danceable", "mood:happy", "mood:energetic"],
    "Indie Pop": ["indie pop", "indie", "catchy", "guitar", "melodic", "mood:happy", "mood:melancholic"],
    "J-pop": ["j-pop", "japanese", "pop", "catchy", "idol", "mood:happy", "mood:energetic"],
    "K-pop": ["k-pop", "korean", "pop", "catchy", "dance", "idol", "mood:happy", "mood:energetic"],
    "Kayōkyoku": ["kayokyoku", "japanese", "pop", "show tunes", "60s-80s", "mood:nostalgic", "mood:melancholic"],
    "Light Music": ["light music", "easy listening", "orchestral", "background", "mood:relaxed", "mood:pleasant"],
    "Music Hall": ["music hall", "variety", "theatrical", "british", "comic", "mood:happy", "mood:entertaining"],
    "Novelty": ["novelty", "comedy", "gimmick", "humorous", "fun", "mood:happy", "mood:funny"],
    "Parody": ["parody pop", "comedy", "humorous", "spoof", "satire", "mood:happy", "mood:funny"],
    "Schlager": ["schlager", "german", "pop", "folk", "catchy", "mood:happy", "mood:nostalgic"],
    "Vocal": ["vocal", "crooner", "standards", "jazz", "orchestral", "mood:romantic", "mood:nostalgic"],

    # =========================================================================
    # R E G G A E
    # =========================================================================
    "Calypso": ["calypso", "trinidad", "caribbean", "rhythmic", "humorous", "mood:happy", "mood:energetic"],
    "Dancehall": ["dancehall", "reggae", "dance", "urban", "mood:energetic", "mood:happy"],
    "Dub": ["dub", "reggae", "bass", "reverb", "echo", "instrumental", "mood:relaxed", "mood:trippy"],
    "Lovers Rock": ["lovers rock", "reggae", "romantic", "soulful", "smooth", "mood:romantic", "mood:relaxed"],
    "Ragga": ["ragga", "dancehall", "digital", "reggae", "jamaican", "mood:energetic", "mood:happy"],
    "Reggae": ["reggae", "groove", "bass", "offbeat", "relaxed", "island", "roots", "positive"],
    "Reggae-Pop": ["reggae-pop", "pop", "reggae", "catchy", "radio-friendly", "mood:happy", "mood:relaxed"],
    "Rocksteady": ["rocksteady", "reggae", "ska", "slow", "soulful", "60s", "mood:relaxed", "mood:romantic"],
    "Roots Reggae": ["roots reggae", "conscious", "bass", "spiritual", "rastafari", "mood:relaxed", "mood:uplifting"],
    "Ska": ["ska", "reggae", "offbeat", "brass", "upbeat", "jamaican", "mood:happy", "mood:energetic"],
    "Soca": ["soca", "trinidad", "carnival", "calypso", "energetic", "mood:happy", "mood:energetic"],

    # =========================================================================
    # B L U E S
    # =========================================================================
    "Boogie Woogie": ["boogie woogie", "piano", "blues", "upbeat", "dance", "mood:happy", "mood:energetic"],
    "Chicago Blues": ["chicago blues", "electric", "urban", "amplified", "harmonica", "mood:soulful", "mood:raw"],
    "Country Blues": ["country blues", "acoustic", "delta", "rural", "fingerpicking", "mood:melancholic", "mood:raw"],
    "Delta Blues": ["delta blues", "acoustic", "slide guitar", "mississippi", "raw", "mood:melancholic", "mood:emotional"],
    "Electric Blues": ["electric blues", "amplified", "guitar", "urban", "chicago", "mood:energetic", "mood:soulful"],
    "Harmonica Blues": ["harmonica blues", "blues harp", "acoustic", "raw", "mood:soulful", "mood:emotional"],
    "Jump Blues": ["jump blues", "upbeat", "saxophone", "dance", "swing", "mood:happy", "mood:energetic"],
    "Louisiana Blues": ["louisiana blues", "swamp blues", "gulf coast", "rhythmic", "mood:groovy", "mood:relaxed"],
    "Modern Electric Blues": ["modern electric blues", "contemporary", "electric", "guitar", "soulful", "mood:energetic", "mood:polished"],
    "Piano Blues": ["piano blues", "boogie woogie", "barrelhouse", "rhythmic", "mood:happy", "mood:energetic"],
    "Rhythm & Blues": ["rhythm and blues blues", "r&b", "blues", "soulful", "dance", "mood:energetic", "mood:romantic"],
    "Texas Blues": ["texas blues", "electric", "guitar", "swing", "stevie ray", "mood:energetic", "mood:soulful"],

    # =========================================================================
    # C L A S S I C A L
    # =========================================================================
    "Baroque": ["baroque", "ornate", "counterpoint", "harpsichord", "mood:elegant", "mood:complex"],
    "Choral": ["choral", "choir", "sacred", "vocal", "polyphony", "mood:spiritual", "mood:uplifting"],
    "Classical": ["classical", "orchestral", "instrumental", "composed", "elegant", "timeless", "symphony", "piano"],
    "Contemporary": ["contemporary classical", "modern", "20th century", "21st century", "avant-garde", "mood:complex", "mood:tense"],
    "Impressionist": ["impressionist", "debussy", "ravel", "atmospheric", "dreamy", "mood:dreamy", "mood:relaxed"],
    "Medieval": ["medieval", "early music", "plainchant", "renaissance", "mood:spiritual", "mood:ancient"],
    "Modern": ["modern classical", "20th century", "atonal", "experimental", "mood:complex", "mood:tense"],
    "Neo-Classical": ["neo-classical", "contemporary", "classical", "minimal", "elegant", "mood:sophisticated", "mood:melancholic"],
    "Neo-Romantic": ["neo-romantic", "romantic", "contemporary", "emotional", "orchestral", "mood:melancholic", "mood:epic"],
    "Opera": ["opera", "vocal", "dramatic", "orchestral", "theatrical", "mood:dramatic", "mood:epic"],
    "Post-Modern": ["post-modern", "contemporary", "eclectic", "experimental", "mood:complex", "mood:ironic"],
    "Renaissance": ["renaissance", "early music", "polyphony", "madrigal", "mood:elegant", "mood:spiritual"],
    "Romantic": ["romantic classical", "emotional", "expressive", "orchestral", "mood:melancholic", "mood:epic"],
        # =========================================================================
    # M I S C  (Non-Music, Children's, Stage & Screen, Brass & Military)
    # =========================================================================
    # Non-Music
    "Audiobook": ["audiobook", "spoken word", "narration", "book", "story", "mood:educational", "mood:relaxed"],
    "Comedy": ["comedy", "humor", "stand-up", "funny", "satire", "mood:funny", "mood:happy"],
    "Dialogue": ["dialogue", "spoken word", "conversation", "talk", "interview", "mood:educational", "mood:casual"],
    "Education": ["educational", "learning", "instructional", "course", "lecture", "mood:educational", "mood:informative"],
    "Field Recording": ["field recording", "ambient", "environmental", "nature", "soundscape", "mood:atmospheric", "mood:meditative"],
    "Interview": ["interview", "spoken word", "conversation", "talk", "q&a", "mood:educational", "mood:casual"],
    "Monolog": ["monologue", "spoken word", "solo", "speech", "theatrical", "mood:dramatic", "mood:thoughtful"],
    "Poetry": ["poetry", "spoken word", "verse", "literary", "emotional", "mood:melancholic", "mood:romantic"],
    "Political": ["political", "speech", "protest", "commentary", "spoken word", "mood:serious", "mood:passionate"],
    "Promotional": ["promotional", "advertising", "commercial", "jingle", "spoken word", "mood:happy", "mood:energetic"],
    "Radioplay": ["radioplay", "audio drama", "theatre", "story", "spoken word", "mood:dramatic", "mood:entertaining"],
    "Religious": ["religious", "sermon", "spiritual", "spoken word", "worship", "mood:spiritual", "mood:uplifting"],
    "Spoken Word": ["spoken word", "speech", "narration", "talk", "words", "mood:educational", "mood:thoughtful"],

    # Children's
    "Educational": ["children's educational", "kids", "learning", "instructional", "family", "mood:happy", "mood:educational"],
    "Nursery Rhymes": ["nursery rhymes", "children's", "kids", "sing-along", "traditional", "mood:happy", "mood:playful"],
    "Story": ["children's story", "storytelling", "kids", "fairytale", "audiobook", "mood:imaginative", "mood:happy"],

    # Stage & Screen
    "Musical": ["musical", "show tunes", "broadway", "theatre", "songs", "mood:dramatic", "mood:happy"],
    "Score": ["film score", "orchestral", "cinematic", "instrumental", "background", "mood:dramatic", "mood:epic"],
    "Soundtrack": ["soundtrack", "film music", "movie", "tv", "video game", "mood:dramatic", "mood:nostalgic"],
    "Theme": ["theme music", "title theme", "tv theme", "signature", "catchy", "mood:happy", "mood:memorable"],

    # Brass & Military
    "Brass Band": ["brass band", "brass", "marching band", "brass ensemble", "traditional", "mood:energetic", "mood:ceremonial"],
    "Marches": ["march", "marching", "military", "patriotic", "brass", "drums", "mood:energetic", "mood:ceremonial"],
    "Military": ["military", "ceremonial", "patriotic", "band", "marches", "mood:ceremonial", "mood:serious"],
}
